[devices]
device1 ansible_host=localhost ansible_port=2221
device2 ansible_host=localhost ansible_port=2222
device3 ansible_host=localhost ansible_port=2223

[devices:vars]
ansible_user=ansible
ansible_password=ansible123
ansible_become_password=ansible123
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
